# path/to/deploy.yml
name: Deploy Model

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run model and show results
        run: |
          python train_model_Transformer.py
          # Assuming train_model_Transformer.py prints the model results
          echo "Model results:"
          # Add any additional commands to display results if needed
          
      # ... other existing steps ...